# Generated by Django 5.1 on 2025-02-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='slug',
        ),
    ]
