# Generated by Django 5.1 on 2025-02-24 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
