# Generated by Django 5.1 on 2025-02-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='colors',
            field=models.CharField(default='black', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sizes',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
