# Generated by Django 5.1 on 2025-03-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0005_orderitem_colors_orderitem_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='recommended_shoes',
            field=models.ManyToManyField(blank=True, to='ship.shopping'),
        ),
    ]
