# Generated by Django 5.1 on 2025-03-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0006_shopping_recommended_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending (COD)', 'Pending (COD)'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending (COD)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
