# Generated by Django 5.1 on 2025-03-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
