# Generated by Django 5.1 on 2025-03-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0009_userprofile_address_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_image/'),
        ),
    ]
